name: rx_provider
description: A simple yet powerful state management inspired from provider.
version: 0.0.5
homepage: https://ensorta.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
